### ISSUE TITLE
3.23 Linux安装、运行单机版Spark

### ISSUE THREAD

**Issue by vieyahn2017** [vieyahn2017/iBlog#260]
Linux安装、运行单机版Spark
https://blog.csdn.net/yzh_1346983557/article/details/81624708

**Comment by vieyahn2017** [comment]
tar   -zxvf  spark-2.4.0-bin-hadoop2.7.tgz

为了操作方便，我将解压得到的spark-2.4.0-bin-hadoop2.7.tgz文件夹改名为spark-2.4.0

## 1 配置环境变量：

vi /etc/profile

export   SPARK_HOME=/usr/java/spark-2.4.0
export   PATH=$PATH:$SPARK_HOME/bin

source /etc/profile


## 2.1 新建spark-env.sh配置文件
copy一份spark-env.sh：cp  spark-env.sh.template spark-env.sh

然后进入vim编辑模式：vim  spark-env.sh，会提示文件已存在，输入“e”进入编辑模式即可。

在文件的最后加上如下配置：

#export SCALA_HOME=/opt/scala-2.13.0
export JAVA_HOME=/usr/java/jdk1.8.0_91
export SPARK_HOME=/usr/java/spark-2.4.0
export SPARK_MASTER_IP=192.168.101.16
#export SPARK_EXECUTOR_MEMORY=512M
#export SPARK_WORKER_MEMORY=1G
#export master=spark://192.168.101.16:7070

最后“Esc”，输入“：”加“wq”保存退出vim编辑模式，最后source spark-env.sh使修改生效。


## 2.2 新建slaves配置文件（子节点配置文件）：

进入spark的conf目录下：cd  /opt/spark-2.3.1/conf/，

copy一份slaves：cp  slaves.template slaves

然后进入vim编辑模式：vim  slaves，会提示文件已存在，输入“e”进入编辑模式即可。

在文件的最后加上如下配置：

localhost

最后“Esc”，输入“：”加“wq”保存退出vim编辑模式，最后source slaves使修改生效。

## 3 启动spark。

进入spark的sbin目录：cd  sbin/

启动spark集群（单机版）： ./start-all.sh

**Comment by vieyahn2017** [comment]
./start-all.sh

```
starting org.apache.spark.deploy.master.Master, logging to /usr/java/spark-2.4.0/logs/spark-vieyahn-org.apache.spark.deploy.master.Master-1-ubuntu64.out
localhost: Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
vieyahn@localhost's password:  [飞]
localhost: starting org.apache.spark.deploy.worker.Worker, logging to /usr/java/spark-2.4.0/logs/spark-vieyahn-org.apache.spark.deploy.worker.Worker-1-ubuntu64.out
```

**Comment by vieyahn2017** [comment]
**单机版已经集成了scala**


不必要单独安装   

For the Scala API, Spark 2.4.0 uses Scala 2.11. You will need to use a compatible Scala version (2.11.x

**Comment by vieyahn2017** [comment]
我单独装了下，报错，就没管了。

@ubuntu64:/usr/yh/deb$ sudo dpkg -i  scala-2.11.12.deb
(Reading database ... 59543 files and directories currently installed.)
Preparing to unpack scala-2.11.12.deb ...
Unpacking scala (2.11.12) over (2.11.12) ...
dpkg: dependency problems prevent configuration of scala:
 scala depends on java6-runtime-headless; however:
  Package java6-runtime-headless is not installed.

dpkg: error processing package scala (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.6.7.1-1) ...
Errors were encountered while processing:
 scala

**Comment by vieyahn2017** [comment]
直接使用 spark-shell进入scala终端     

或者pyspark进入python终端

**Comment by vieyahn2017** [comment]
## spark单机版计算测试
https://blog.csdn.net/luoganttcc/article/details/78563635
2017年11月17日 17:21:37 luoganttcc 阅读数：325

```python
import math
import time
from pyspark import SparkConf, SparkContext
from pyspark.sql import SQLContext

conf=SparkConf().setAppName('IsPrime')
sc=SparkContext(conf=conf)
sqlCtx=SQLContext(sc)
#sqlCtx=SQLContext.read(sc)

def IsPrime(n):
    if not isinstance(n, int):
        raise TypeError("argument passed to is_prime is not of 'int' type")
    if n < 2:
        return False
    if n == 2:
        return True
    max = int(math.ceil(math.sqrt(n)))
    i = 2
    while i <= max:
        if n % i == 0:
            return False
        i += 1
    return True


t1=time.time()
rdd=sc.parallelize(range(8*10**6))

result=rdd.filter(IsPrime).count()
print(result)
print('spark time=',time.time()-t1)



s1=time.time()

num=0
for n in range(8*10**6):
    if IsPrime(n):
        num=num+1
print(num)

print('python time',time.time()-s1)
```

运行结果：
```
539777
spark time= 74.22103095054626
539777
python time 181.73229908943176
```
spark 比Python 串行计算快一倍以上。

**Comment by vieyahn2017** [comment]
我直接在pyspark命令行下测试，会报错   
```
>>> sc=SparkContext(SparkConf())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/java/spark-2.4.0/python/pyspark/context.py", line 115, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/usr/java/spark-2.4.0/python/pyspark/context.py", line 314, in _ensure_initialized
    callsite.function, callsite.file, callsite.linenum))
ValueError: Cannot run multiple SparkContexts at once; existing SparkContext(app=PySparkShell, master=local[*]) created by <module> at /usr/java/spark-2.4.0/python/pyspark/shell.py:41
```

**Comment by vieyahn2017** [comment]
明显在pyspark下不能新建上下文，所以可以用：
```python
from pyspark import SparkConf, SparkContext
sc=SparkContext._active_spark_context
···

**Comment by vieyahn2017** [comment]
另外查看pyspark环境的py版本：
```
>>> import sys
>>> print sys.version
2.7.6 (default, Mar 22 2014, 22:59:56)
[GCC 4.8.2]
>>> print sys.version_info
sys.version_info(major=2, minor=7, micro=6, releaselevel='final', serial=0)

```

**Comment by vieyahn2017** [comment]
测试代码最新如下   
（python2.7用xrange代替range提高性能）
```python
import math
import time
from pyspark import SparkConf, SparkContext
sc=SparkContext._active_spark_context

MAX_NUM = 100000

def IsPrime(n):
    if not isinstance(n, int):
        raise TypeError("argument passed to is_prime is not of 'int' type")
    if n < 2:
        return False
    if n == 2:
        return True
    max = int(math.ceil(math.sqrt(n)))
    i = 2
    while i <= max:
        if n % i == 0:
            return False
        i += 1
    return True


t1=time.time()
rdd=sc.parallelize(xrange(MAX_NUM))
result=rdd.filter(IsPrime).count()
print(result)
print('spark time=',time.time()-t1)


s1=time.time()
list = [n for n in xrange(MAX_NUM) if IsPrime(n)]
num=len(list)
print(num)
print('python time',time.time()-s1)

print('===test ok====')

```

运行结果：
```
('spark time=', 0.7043089866638184)
('python time', 0.36194705963134766)

```

**Comment by vieyahn2017** [comment]
spark-shell里面
```scala
import org.apache.spark.{SparkConf, SparkContext}
val conf = new SparkConf().setAppName("FPGrowthTest")
val sc = new SparkContext(conf)
```
也要报错
org.apache.spark.SparkException: Only one SparkContext may be running in this JVM (see SPARK-2243). To ignore this error, set spark.driver.allowMultipleContexts = true. The currently running SparkContext was created at:
org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:926)
org.apache.spark.repl.Main$.createSparkSession(Main.scala:106)
<init>(<console>:15)
<init>(<console>:43)
<init>(<console>:45)
.<init>(<console>:49)
.<clinit>(<console>)
.$print$lzycompute(<console>:7)
.$print(<console>:6)
$print(<console>)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:793)
scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1054)
scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:645)
scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:644)
scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
  at org.apache.spark.SparkContext$$anonfun$assertNoOtherContextIsRunning$2.apply(SparkContext.scala:2483)
  at org.apache.spark.SparkContext$$anonfun$assertNoOtherContextIsRunning$2.apply(SparkContext.scala:2479)
  at scala.Option.foreach(Option.scala:257)
  at org.apache.spark.SparkContext$.assertNoOtherContextIsRunning(SparkContext.scala:2479)
  at org.apache.spark.SparkContext$.markPartiallyConstructed(SparkContext.scala:2568)
  at org.apache.spark.SparkContext.<init>(SparkContext.scala:85)
  ... 51 elided

**Comment by vieyahn2017** [comment]
后面才探索出，需要
```scala
val sc = org.apache.spark.repl.Main.sparkContext
```
是结合 反射 和Spark shell的原理相关帖子探索出来的

**Comment by vieyahn2017** [comment]
python直接可以用
```python
dir(SparkContext)
```

scala要用反射
```scala
val clazz = Class.forName("org.apache.spark.SparkContext")
val methods = clazz.getDeclaredMethods()
for (m <- methods) { println(m) }
```
