### ISSUE TITLE
4.20 Python 调试器之pdb

### ISSUE THREAD

**Issue by vieyahn2017** [vieyahn2017/iBlog#277]
Python 调试器之pdb
https://www.cnblogs.com/xiaohai2003ly/p/8529472.html

**Comment by vieyahn2017** [comment]
使用PDB的方式有两种:

1. 单步执行代码,通过命令 python -m pdb xxx.py 启动脚本，进入单步执行模式

2. 第二种方法是import pdb 之后，直接在代码里需要调试的地方放一个pdb.set_trace()，就可以设置一个断点， 程序会在pdb.set_trace()暂停并进入pdb调试环境，可以用pdb 变量名查看变量，或者c继续运行

**Comment by vieyahn2017** [comment]
```
s：（step）执行下一条命令 进入函数

n：（next）执行下一条语句 不进入函数

r：（return）执行当前运行函数到结束

c：（continue）继续执行，直到遇到下一条断点

p expression：（print）输出expression的值

q：（quit）退出debug

```

**Comment by vieyahn2017** [comment]
### pdb命令行：

1）进入命令行Debug模式，python -m pdb xxx.py

2）h：（help）帮助

3）w：（where）打印当前执行堆栈

4）d：（down）执行跳转到在当前堆栈的深一层（个人没觉得有什么用处）

5）u：（up）执行跳转到当前堆栈的上一层

6）b：（break）添加断点

 b 列出当前所有断点，和断点执行到统计次数

 b line_no：当前脚本的line_no行添加断点

 b filename:line_no：脚本filename的line_no行添加断点

 b function：在函数function的第一条可执行语句处添加断点

7）tbreak：（temporary break）临时断点

 在第一次执行到这个断点之后，就自动删除这个断点，用法和b一样

8）cl：（clear）清除断点

cl 清除所有断点

cl bpnumber1 bpnumber2... 清除断点号为bpnumber1,bpnumber2...的断点

cl lineno 清除当前脚本lineno行的断点

cl filename:line_no 清除脚本filename的line_no行的断点

9）disable：停用断点，参数为bpnumber，和cl的区别是，断点依然存在，只是不启用

10）enable：激活断点，参数为bpnumber

11）s：（step）执行下一条命令

如果本句是函数调用，则s会执行到函数的第一句

12）n：（next）执行下一条语句

如果本句是函数调用，则执行函数，接着执行当前执行语句的下一条。

13）r：（return）执行当前运行函数到结束

14）c：（continue）继续执行，直到遇到下一条断点

15）l：（list）列出源码

 l 列出当前执行语句周围11条代码

 l first 列出first行周围11条代码

 l first second 列出first--second范围的代码，如果second<first，second将被解析为行数

16）a：（args）列出当前执行函数的函数

17）p expression：（print）输出expression的值

18）pp expression：好看一点的p expression

19）run：重新启动debug，相当于restart

20）q：（quit）退出debug

21）j lineno：（jump）设置下条执行的语句函数

只能在堆栈的最底层跳转，向后重新执行，向前可直接执行到行号

22）unt：（until）执行到下一行（跳出循环），或者当前堆栈结束

23）condition bpnumber conditon，给断点设置条件，当参数condition返回True的时候bpnumber断点有效，否则bpnumber断点无效

**Comment by vieyahn2017** [comment]
### Python 代码调试技巧
https://www.ibm.com/developerworks/cn/linux/l-cn-pythondebugger/index.html

（格式排版更舒服）

使用 pdb 进行调试
pdb 是 python 自带的一个包，为 python 程序提供了一种交互的源代码调试功能，主要特性包括设置断点、单步调试、进入函数调试、查看当前代码、查看栈片段、动态改变变量的值等。

**Comment by vieyahn2017** [comment]
### python pdb调试
https://www.cnblogs.com/chencheng/archive/2013/07/07/3161778.html
在交互环境中通常使用pdb.run来调试：

```python
import pdb

def pdb_test(arg):
    for i in range(arg):
        print(i)
    return arg

pdb.run("pdb_test(3)")

```


#### b 函数名、行号：

打断点，b可以查询所有的断点。

(Pdb) b pdb_test
Breakpoint 1 at c:\users\plpcc\desktop\pdbtest.py:3
(Pdb) b
Num Type         Disp Enb   Where
1   breakpoint   keep yes   at c:\users\plpcc\desktop\pdbtest.py:3
 

#### c：
运行程序，直到遇到断点。

(Pdb) c
> c:\users\plpcc\desktop\pdbtest.py(4)pdb_test()
-> for i in range(arg):
 

#### l：

查看断点周围的代码

(Pdb) l
  1     import pdb
  2     
  3 B   def pdb_test(arg):
  4  ->     for i in range(arg):
  5             print(i)
  6         return arg
  7     
  8     pdb.run("pdb_test(3)")
 

#### a:

查看参数

(Pdb) a
arg = 3
 

#### s, n：

单步运行,区别s会进入路径中的函数，n不会进入 

#### p：

查看表达式的值

(Pdb) p i
0


#### condition：

条件断点，只有条件为true断点才命中

> c:\users\plpcc\desktop\pdbtest.py(5)pdb_test()
-> print(i)
(Pdb) l
  1     import pdb
  2     
  3     def pdb_test(arg):
  4         for i in range(arg):
  5 B->         print(i)
  6         return arg
  7     
  8     pdb.run("pdb_test(3)")
[EOF]
(Pdb) b
Num Type         Disp Enb   Where
2   breakpoint   keep yes   at c:\users\plpcc\desktop\pdbtest.py:5
(Pdb) condition 2 i==1   //i==1时才触发断点2
New condition set for breakpoint 2.
(Pdb) b
Num Type         Disp Enb   Where
2   breakpoint   keep yes   at c:\users\plpcc\desktop\pdbtest.py:5
    stop only if i==1
(Pdb) c
0                       //i==0直接打印未断住
> c:\users\plpcc\desktop\pdbtest.py(5)pdb_test()
-> print(i)             //触发断点，i==1
(Pdb) p i
1

#### bt: 查看调用堆栈

(Pdb) bt
  c:\python33\lib\bdb.py(405)run()
-> exec(cmd, globals, locals)
  <string>(1)<module>()
> c:\users\plpcc\desktop\pdbtest.py(5)pdb_test()
-> print(i)


#### r：执行到函数返回

(Pdb) r
1
2
--Return--
> c:\users\plpcc\desktop\pdbtest.py(6)pdb_test()->3 //代码位置、函数返回值->3
-> return arg                                       //代码位置的语句
(Pdb) l
  1     import pdb
  2     
  3     def pdb_test(arg):
  4         for i in range(arg):
  5             print(i)
  6  ->     return arg
  7     
  8     pdb.run("pdb_test(3)")
 

通过pdb.set_trace() 在代码中指定位置嵌入一个断点，通常可以通过调试开关来控制

```python
import pdb

__DEBUG__ = True

def pdb_test(arg):
    if True == __DEBUG__:
        pdb.set_trace()
    for i in range(arg):
        print(i)
    return arg

pdb_test(3)
```


运行后在pdb.set_trace()位置被断住，当__DEBUG__ = False，代码正常运行

> c:\users\plpcc\desktop\pdbtest.py(8)pdb_test()
-> for i in range(arg):
(Pdb) l
  3     __DEBUG__ = True
  4     
  5     def pdb_test(arg):
  6         if True == __DEBUG__:
  7             pdb.set_trace()
  8  ->     for i in range(arg):
  9             print(i)
 10         return arg
 11     
 12     pdb_test(3)
[EOF]
 

通过pdb.pm()进行事后调试，可以跟踪异常程序最后的堆载信息：

Traceback (most recent call last):
  File "C:\Users\plpcc\Desktop\pdbTest.py", line 13, in <module>
    pdb_test(3)
  File "C:\Users\plpcc\Desktop\pdbTest.py", line 10, in pdb_test
    1/0
ZeroDivisionError: division by zero
>>> import pdb
>>> pdb.pm()
> c:\users\plpcc\desktop\pdbtest.py(10)pdb_test()
-> 1/0
(Pdb) l
  5     def pdb_test(arg):
  6         if True == __DEBUG__:
  7             pdb.set_trace()
  8         for i in range(arg):
  9             print(i)
 10  ->         1/0
 11         return arg
 12     
 13     pdb_test(3)
